CREATE DATABASE SUCO_VENDAS

USE SUCO_VENDAS

--TABELA DE CLIENTES
--CPF do cliente
--O nome completo do cliente
--Endereço com Rua, bairro, cidade, estado e CEP
--Data de nascimento
--A idade
--Gênero
--O limite do crédito do cliente para ele comprar produtos na empresa
--O volume mínimo de produtos que ele pode comprar
--Se ele já realizou a primeira compra.

CREATE TABLE [TABELA DE CLIENTES]
([CPF] [CHAR] (11),
[NOME] [VARCHAR] (100),
[ENDERECO1] [VARCHAR] (150),
[ENDERECO2] [VARCHAR] (150),
[BAIRRO] [VARCHAR] (50),
[CIDADE] [VARCHAR] (50),
[ESTADO] [CHAR] (2),
[CEP] [CHAR] (8),
[DATA DE NASCIMENTO] [DATE],
[IDADE] [SMALLINT],
[SEXO] [CHAR] (1),
[LIMITE DE CREDITO] [MONEY],
[VOLUME DE COMPRA] [FLOAT],
[PRIMEIRA COMPRA] [BIT]);

--Nome da tabela deve ser TABELA DE VENDEDORES.
--Vendedor tem como chave o número interno da matrícula (Nome do campo MATRICULA) que deve ser um texto de 5 posições.

--O nome do vendedor (Nome do campo NOME) deve ser um texto de 100 posições.

--% de comissão. Este campo (Nome do campo PERCENTUAL COMISSÃO) representa quantos % de comissão o vendedor ganha sobre cada venda.

CREATE TABLE [TABELA DE VENDEDORES]
([MATRICULA] [VARCHAR] (5),
[NOME] [VARCHAR] (100),
[PERCENTUAL COMISSAO] [FLOAT]);

INSERT INTO [TABELA DE VENDEDORES]
([MATRICULA], [NOME], [PERCENTUAL COMISSAO])
VALUES
('00235', 'Márcio Almeida Silva', 0.08),
('00236','Cláudia Morais', 0.08)


CREATE TABLE [TABELA DE PRODUTOS](
	[CODIGO DO PRODUTO] [varchar](20) NULL,
	[NOME DO PRODUTO] [varchar](150) NULL,
	[EMBALAGEM] [varchar](50) NULL,
	[TAMANHO] [varchar](50) NULL,
	[SABOR] [varchar](50) NULL,
	[PRECO DE LISTA] [smallmoney] NULL
) ON [PRIMARY]

--Insere linhas na tabela
INSERT INTO [TABELA DE PRODUTOS]
([CODIGO DO PRODUTO],
[NOME DO PRODUTO],
[EMBALAGEM],
[TAMANHO],
[SABOR],
[PRECO DE LISTA])
VALUES 
('1040107', 'Light - 350 ml - Melância', 'Lata', '350 ml', 'Melancia', 4.56)

INSERT INTO [TABELA DE PRODUTOS]
([CODIGO DO PRODUTO],
[NOME DO PRODUTO],
[EMBALAGEM],
[TAMANHO],
[SABOR],
[PRECO DE LISTA])
VALUES 
('1037797', 'Clean - 2 Litros - Laranja', 'PET', '2 Litros', 'Laranja', 16.01)

INSERT INTO [TABELA DE PRODUTOS]
([CODIGO DO PRODUTO],
[NOME DO PRODUTO],
[EMBALAGEM],
[TAMANHO],
[SABOR],
[PRECO DE LISTA])
VALUES 
('1000889', 'Sabor da Montanha - 700 ml - Uva', 'Garrafa', '700 ml', 'Uva', 6.31)

--Incluindo registros errados
INSERT INTO [TABELA DE PRODUTOS]
([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA])
VALUES
('544931', 'Frescor do Verão - 350 ml - Limão', 'PET', '350 ml','Limão',3.20)

INSERT INTO [TABELA DE PRODUTOS]
([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA])
VALUES
('1078680', 'Frescor do Verão - 470 ml - Manga', 'Lata', '470 ml','Manga',5.18)

--Corrigindo registros errados
UPDATE [TABELA DE PRODUTOS]
SET [EMBALAGEM] = 'Lata',
[PRECO DE LISTA] = 2.46
WHERE [CODIGO DO PRODUTO] = '544931'

UPDATE [TABELA DE PRODUTOS]
SET [EMBALAGEM] = 'Garrafa'
WHERE [CODIGO DO PRODUTO] = '1078680'

UPDATE [TABELA DE VENDEDORES]
SET [NOME] = 'Cláudia Morais Sousa'
WHERE [MATRICULA] = '00236'

UPDATE [TABELA DE VENDEDORES]
SET [PERCENTUAL COMISSAO] = 0.11
WHERE [MATRICULA] = '00235'

--Deleta linha da tabela
DELETE FROM [TABELA DE PRODUTOS]
WHERE [CODIGO DO PRODUTO] = '1078680'

DELETE FROM [TABELA DE VENDEDORES] 
WHERE [MATRICULA] = '00235';

INSERT INTO [TABELA DE PRODUTOS]
VALUES
('788975', 'Pedaços de Frutas - 1,5 Litros - Maça', 'PET', '1,5 Litros', 'Maça', 18.01)

INSERT INTO [TABELA DE VENDEDORES]
([NOME], [MATRICULA], [PERCENTUAL COMISSAO])
VALUES
('Alberto de Sá Verneck', '00239', 0.08)

INSERT INTO [TABELA DE PRODUTOS]
VALUES
('1002767', 'Videira do Campo - 700 ml - Cereja/Maça', 'Garrafa', '700 ml', 'Cereja/Maca', 8.41)

ALTER TABLE [TABELA DE PRODUTOS] 
ADD CONSTRAINT PK_TABELA_DE_PRODUTOS
PRIMARY KEY CLUSTERED ([CODIGO DO PRODUTO])

ALTER TABLE [TABELA DE PRODUTOS]
ALTER COLUMN [CODIGO DO PRODUTO]
VARCHAR(20) NOT NULL;

ALTER TABLE [TABELA DE VENDEDORES]
ALTER COLUMN [MATRICULA]
VARCHAR(5) NOT NULL;

ALTER TABLE [TABELA DE VENDEDORES]
ADD CONSTRAINT PK_TABELA_DE_VENDEDORES
PRIMARY KEY CLUSTERED ([MATRICULA])

ALTER TABLE [TABELA DE VENDEDORES]
ALTER COLUMN [PERCENTUAL COMISSAO]
FLOAT NOT NULL;

ALTER TABLE [TABELA DE CLIENTES]
ALTER COLUMN [CPF]
CHAR(11) NOT NULL;

ALTER TABLE [TABELA DE CLIENTES]
ADD CONSTRAINT PK_TABELA_DE_CLIENTES
PRIMARY KEY CLUSTERED ([CPF])

USE [SUCO_VENDAS]
GO

INSERT INTO [dbo].[TABELA DE CLIENTES]
           ([CPF]
           ,[NOME]
           ,[ENDERECO1]
           ,[ENDERECO2]
           ,[BAIRRO]
           ,[CIDADE]
           ,[ESTADO]
           ,[CEP]
           ,[DATA DE NASCIMENTO]
           ,[IDADE]
           ,[SEXO]
           ,[LIMITE DE CREDITO]
           ,[VOLUME DE COMPRA]
           ,[PRIMEIRA COMPRA])
     VALUES
           ('12345678910'
           ,'João da Silva'
           ,'Rua Projetada A'
           ,'Numero 233'
           ,'Copacabana'
           ,'Rio de Janeiro'
           ,'RJ'
           ,'20000000'
           ,'1965-03-21'
           ,53
           ,'M'
           ,2000.00
           ,3000.23
           ,1)
GO

CREATE TABLE [TABELA DE VENDEDORES]
([MATRICULA] VARCHAR(5) NOT NULL,
[NOME] VARCHAR(100) NULL,
[PERCENTUAL COMISSAO] FLOAT NOT NULL
CONSTRAINT [PK TABELA DE VENDEDORES] PRIMARY KEY CLUSTERED ([MATRICULA]))

INSERT INTO [TABELA DE VENDEDORES]
([NOME], [MATRICULA], [PERCENTUAL COMISSAO])
VALUES
('Alberto de Sá Verneck', '00239', 0.08)

--Seleciona dados do banco para exibição
SELECT [CPF]
      ,[NOME]
FROM [TABELA DE CLIENTES]

SELECT [NOME]
      ,[CPF]
FROM [TABELA DE CLIENTES]

SELECT * FROM [TABELA DE CLIENTES]

SELECT [CPF] AS IDENTIFICADOR
      ,[NOME] AS [NOME DO CLIENTE]
FROM [TABELA DE CLIENTES]

SELECT [MATRICULA] AS IDENTIFICADOR,
[NOME] AS [NOME DO VENDEDOR]
FROM [TABELA DE VENDEDORES]

SELECT * FROM [TABELA DE PRODUTOS]
WHERE [CODIGO DO PRODUTO] = '1000889'

DELETE FROM [TABELA DE PRODUTOS] 
WHERE [CODIGO DO PRODUTO] = '1000889' --Condição lógica de filtro

SELECT [CODIGO DO PRODUTO], [NOME DO PRODUTO] 
FROM [TABELA DE PRODUTOS]
WHERE [CODIGO DO PRODUTO] = '1000889'

SELECT * 
FROM [TABELA DE PRODUTOS]
WHERE [SABOR] = 'Uva'

SELECT * 
FROM [TABELA DE PRODUTOS]
WHERE [SABOR] = 'Limão'

--Aumenta em 10% o valors dos sucos sabor limão
UPDATE [TABELA DE PRODUTOS] 
SET [PRECO DE LISTA] = 1.1 * [PRECO DE LISTA]
WHERE [SABOR] = 'Limão'

SELECT * FROM [TABELA DE VENDEDORES]
UPDATE [TABELA DE VENDEDORES]
SET [PERCENTUAL COMISSAO] = 1.1 * [PERCENTUAL COMISSAO]
WHERE [MATRICULA] = '00239'

--Filtragem de dados em tabela
SELECT * FROM [TABELA DE PRODUTOS]
WHERE [EMBALAGEM] = 'PET'

SELECT * FROM [TABELA DE PRODUTOS]
WHERE [PRECO DE LISTA] = 8.008

SELECT * FROM [TABELA DE PRODUTOS]
WHERE [PRECO DE LISTA] < 10

SELECT * FROM [TABELA DE PRODUTOS]
WHERE [PRECO DE LISTA] > 10

SELECT * FROM [TABELA DE PRODUTOS]
WHERE [PRECO DE LISTA] >= 13.312

SELECT * FROM [TABELA DE PRODUTOS]
WHERE EMBALAGEM <= 'Lata'

SELECT * FROM [TABELA DE PRODUTOS]
WHERE EMBALAGEM <> 'Lata'

SELECT * FROM [TABELA DE VENDEDORES]
WHERE [PERCENTUAL COMISSAO] > 0.10

SELECT * FROM [TABELA DE CLIENTES]

SELECT * FROM [TABELA DE CLIENTES]
WHERE [DATA DE NASCIMENTO] = '1995-09-11'

SELECT * FROM [TABELA DE CLIENTES]
WHERE [DATA DE NASCIMENTO] >= '1995-09-11'

SELECT * FROM [TABELA DE CLIENTES]
WHERE [DATA DE NASCIMENTO] <= '1995-09-11'

SELECT * FROM  [TABELA DE CLIENTES]
WHERE YEAR ([DATA DE NASCIMENTO]) = 1995

SELECT * FROM [TABELA DE CLIENTES]
WHERE MONTH ([DATA DE NASCIMENTO]) = 9

SELECT * FROM [TABELA DE CLIENTES]
WHERE DAY ([DATA DE NASCIMENTO]) = 12

-- AND
-- VERDADEIRO E VERDADEIRO = VERDADEIRO
-- VERDADEIRO E FALSO = FALSO
-- FALSO E VERDADEIRO = FALSO
-- FALSO E FALSO = FALSO

-- OR
-- VERDADEIRO OU VERDADEIRO = VERDADEIRO
-- VERDADEIRO OU FALSO = VERDADEIRO
-- FALSO OU VERDADEIRO = VERDADEIRO
-- FALSO OU FALSO = FALSO

SELECT * FROM TABELA WHERE FILTRO -- RETORNA LINHAS ONDE O FILTRO É = VERDADEIRO

--Filtros compostos
SELECT * FROM [TABELA DE CLIENTES]
WHERE DAY ([DATA DE NASCIMENTO]) = 12 OR [BAIRRO] = 'Tijuca'

SELECT * FROM [TABELA DE CLIENTES]
WHERE YEAR ([DATA DE NASCIMENTO]) = 1995 AND [SEXO] = 'F'

SELECT * FROM [TABELA DE VENDEDORES] 
WHERE [PERCENTUAL COMISSAO] > 0.09 OR [MATRICULA] = 00236